export const cardsData = [
  [
    /* For Men */
    {
      id: 1,
      type: "Jacket",
      icon1: "/clothes/Men/Jacket/TommyHilfiger/Black/1.jpg",
      icon2: "/clothes/Men/Jacket/TommyHilfiger/Black/2.jpg",
      icon3: "/clothes/Men/Jacket/TommyHilfiger/Black/3.jpg",
      icon4: "/clothes/Men/Jacket/TommyHilfiger/Red/1.jpg",
      brand: "Tommy Hilfiger",
      name: "",
      colors: [
        {
          name: "Black",
          class: "bg-black",
          selectedClass: "ring-black",
        },
        { name: "Red", class: "bg-red-900", selectedClass: "ring-red-900" },
      ],
      sizes: [
        { name: "S", inStock: true },
        { name: "M", inStock: true },
        { name: "L", inStock: true },
        { name: "XL", inStock: true },
        { name: "XXL", inStock: true },
      ],
      reviews: [{ average: 3 }, { totalCount: 25 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$500",
      path: "/",
    },
    {
      id: 2,
      type: "Jeans",
      icon1: "/clothes/Men/Jeans/Levis/Black/1.jpg",
      icon2: "/clothes/Men/Jeans/Levis/Blue/2.jpg",
      icon3: "/clothes/Men/Jeans/Levis/DarkBlue/3.jpg",
      icon4: "/clothes/Men/Jeans/Levis/SkyBlue/3.jpg",
      alt: "",
      brand: "Levis",
      name: "Relaxed Straight",
      colors: [
        {
          name: "Black",
          class: "bg-black",
          selectedClass: "ring-black",
        },
        { name: "Blue", class: "bg-blue-950", selectedClass: "ring-blue-950" },
        {
          name: "Dark Blue",
          class: "bg-red-900",
          selectedClass: "ring-red-900",
        },
        {
          name: "Sky Blue",
          class: "bg-blue-500",
          selectedClass: "ring-blue-500",
        },
      ],
      sizes: [
        { name: "29", inStock: true },
        { name: "30", inStock: true },
        { name: "31", inStock: true },
        { name: "32", inStock: true },
        { name: "33", inStock: true },
        { name: "34", inStock: true },
        { name: "36", inStock: true },
        { name: "38", inStock: true },
        { name: "40", inStock: true },
      ],
      reviews: [{ average: 1 }, { totalCount: 11 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$300",
      path: "/",
    },
    {
      id: 3,
      type: "Shirt",
      icon1: "/clothes/Men/Shirt/Wrangler/1.jpg",
      icon2: "/clothes/Men/Shirt/Wrangler/2.jpg",
      icon3: "/clothes/Men/Shirt/Wrangler/3.jpg",
      icon4: "/clothes/Men/Shirt/Wrangler/1.jpg",
      alt: "",
      brand: "Wrangler",
      name: "GRAPHIC TEE",
      colors: [
        { name: "Gray", class: "bg-gray-500", selectedClass: "bg-gray-500" },
      ],
      sizes: [
        { name: "M", inStock: true },
        { name: "XL", inStock: true },
        { name: "L", inStock: false },
        { name: "XXL", inStock: false },
      ],
      reviews: [{ average: 3 }, { totalCount: 22 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
    {
      id: 4,
      type: "Shorts",
      icon1: "/clothes/Men/Shorts/Adidas/1.jpg",
      icon2: "/clothes/Men/Shorts/Adidas/2.jpg",
      icon3: "/clothes/Men/Shorts/Adidas/3.jpg",
      icon4: "/clothes/Men/Shorts/Adidas/4.jpg",
      alt: "",
      brand: "Adidas",
      name: "Originals Short",
      colors: [
        { name: "Blue", class: "bg-blue-900", selectedClass: "bg-grey-900" },
      ],
      sizes: [
        { name: "M", inStock: true },
        { name: "XL", inStock: false },
        { name: "L", inStock: true },
        { name: "XXL", inStock: false },
      ],
      reviews: [{ average: 3 }, { totalCount: 22 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
    {
      id: 5,
      type: "Suit",
      icon1: "/clothes/Men/Suits/CalvinKlein/1.jpg",
      icon2: "/clothes/Men/Suits/CalvinKlein/2.jpg",
      icon3: "/clothes/Men/Suits/CalvinKlein/3.jpg",
      icon4: "/clothes/Men/Suits/CalvinKlein/4.jpg",
      alt: "",
      brand: "Calvin Klein",
      name: "MODERN WOOL BLEND REGULAR BLAZER",
      colors: [{ name: "Black", class: "bg-black", selectedClass: "bg-black" }],
      sizes: [
        { name: "M", inStock: false },
        { name: "XL", inStock: false },
        { name: "L", inStock: false },
        { name: "XXL", inStock: true },
      ],
      reviews: [{ average: 5 }, { totalCount: 89 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
  ],
  [
    /* For Women */
    {
      id: 6,
      type: "Dress",
      icon1: "/clothes/Women/Dress/CalvinKlein/3.jpg",
      icon2: "/clothes/Women/Dress/CalvinKlein/2.jpg",
      icon3: "/clothes/Women/Dress/CalvinKlein/1.jpg",
      icon4: "/clothes/Women/Dress/CalvinKlein/4.jpg",
      alt: "",
      brand: "Calvin Klein",
      name: "WOVEN LABEL RIB POLO LS DRESS",
      colors: [
        { name: "Black", class: "bg-black", selectedClass: "bg-black" },
        { name: "Pink", class: "bg-pink-500", selectedClass: "bg-pink-500" },
      ],
      sizes: [
        { name: "1-2 Months", inStock: true },
        { name: "2-4 Months", inStock: true },
        { name: "6-9 Months", inStock: true },
        { name: "1-2 Years", inStock: true },
      ],
      reviews: [{ average: 5 }, { totalCount: 89 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$200",
      path: "/",
    },
    {
      id: 7,
      type: "Jeans",
      icon1: "/clothes/Women/Jeans/CalvinKlein/1.jpg",
      icon2: "/clothes/Women/Jeans/CalvinKlein/2.jpg",
      icon3: "/clothes/Women/Jeans/CalvinKlein/1.jpg",
      icon4: "/clothes/Women/Jeans/CalvinKlein/2.jpg",
      alt: "",
      brand: "Calvin Klein",
      name: "HR WIDE - MID STONE BLUE",
      colors: [
        { name: "Blue", class: "bg-blue-950", selectedClass: "ring-blue-950" },
      ],
      sizes: [
        { name: "24", inStock: true },
        { name: "25", inStock: true },
        { name: "26", inStock: true },
        { name: "28", inStock: true },
        { name: "29", inStock: false },
        { name: "30", inStock: true },
      ],
      reviews: [{ average: 4 }, { totalCount: 55 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$200",
      path: "/",
    },
    {
      id: 8,
      type: "Shirt",
      icon1: "/clothes/Women/Shirt/Adidas/1.jpg",
      icon2: "/clothes/Women/Shirt/Adidas/2.jpg",
      icon3: "/clothes/Women/Shirt/Adidas/3.jpg",
      icon4: "/clothes/Women/Shirt/Adidas/1.jpg",
      alt: "",
      brand: "Adidas",
      name: "Z.N.E. Tee",
      colors: [
        { name: "Blue", class: "bg-blue-950", selectedClass: "ring-blue-950" },
        {
          name: "Flesh",
          class: "bg-green-200",
          selectedClass: "ring-green-200",
        },
      ],
      sizes: [
        { name: "S", inStock: true },
        { name: "M", inStock: true },
        { name: "L", inStock: true },
        { name: "XS", inStock: true },
        { name: "XL", inStock: false },
        { name: "XXL", inStock: false },
      ],
      reviews: [{ average: 2 }, { totalCount: 33 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
    {
      id: 9,
      type: "Skirt",
      icon1: "/clothes/Women/Skirt/ONLY/1.jpg",
      icon2: "/clothes/Women/Skirt/ONLY/2.jpg",
      icon3: "/clothes/Women/Skirt/ONLY/1.jpg",
      icon4: "/clothes/Women/Skirt/ONLY/2.jpg",
      alt: "",
      brand: "ONLY",
      name: "ONLCATH PLISSE CHECK SKIRT XT WVN",
      colors: [
        { name: "Blue", class: "bg-black", selectedClass: "ring-black" },
      ],
      sizes: [
        { name: "S", inStock: true },
        { name: "M", inStock: true },
        { name: "L", inStock: true },
        { name: "XS", inStock: true },
        { name: "XL", inStock: false },
        { name: "XXL", inStock: false },
      ],
      reviews: [{ average: 4 }, { totalCount: 32 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
    {
      id: 10,
      type: "Trousers",
      icon1: "/clothes/Women/Trousers/Adidas/1.jpg",
      icon2: "/clothes/Women/Trousers/Adidas/2.jpg",
      icon3: "/clothes/Women/Trousers/Adidas/1.jpg",
      icon4: "/clothes/Women/Trousers/Adidas/3.jpg",
      alt: "",
      brand: "Adidas",
      name: "Future Icons 3-Stripes Regular Pants",
      colors: [
        { name: "White", class: "bg-white", selectedClass: "ring-gray-500" },
      ],
      sizes: [
        { name: "S", inStock: true },
        { name: "M", inStock: true },
        { name: "L", inStock: true },
        { name: "XS", inStock: true },
        { name: "XL", inStock: false },
        { name: "XXL", inStock: false },
      ],
      reviews: [{ average: 3 }, { totalCount: 66 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$100",
      path: "/",
    },
  ],
  [
    /* For Kids */
    {
      id: 11,
      type: "Dress",
      icon1: "/clothes/Kids/Dress/Levis/1.jpg",
      icon2: "/clothes/Kids/Dress/Levis/2.jpg",
      icon3: "/clothes/Kids/Dress/Levis/2.jpg",
      icon4: "/clothes/Kids/Dress/Levis/1.jpg",
      alt: "",
      brand: "Levi's",
      name: "Levi's dress",
      colors: [
        {
          name: "Orange",
          class: "bg-orange-400",
          selectedClass: "ring-orange-400",
        },
      ],
      sizes: [
        { name: "10 Years", inStock: true },
        { name: "11 Years", inStock: false },
        { name: "12 Years", inStock: true },
        { name: "13 Years", inStock: false },
        { name: "14 Years", inStock: true },
        { name: "15 Years", inStock: false },
        { name: "16 Years", inStock: false },
      ],
      reviews: [{ average: 5 }, { totalCount: 886 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$90",
      path: "/",
    },
    {
      id: 12,
      type: "Jacket",
      icon1: "/clothes/Kids/Jacket/Lacoste/1.jpg",
      icon2: "/clothes/Kids/Jacket/Lacoste/2.jpg",
      icon3: "/clothes/Kids/Jacket/Lacoste/3.jpg",
      icon4: "/clothes/Kids/Jacket/Lacoste/1.jpg",
      alt: "",
      brand: "Lacoste",
      name: "Quilted Plaid Overshirt",
      colors: [
        {
          name: "White",
          class: "bg-blue-900",
          selectedClass: "ring-blue-900",
        },
      ],
      sizes: [
        { name: "2 Years", inStock: true },
        { name: "4 Years", inStock: false },
        { name: "5 Years", inStock: false },
        { name: "6 Years", inStock: true },
        { name: "8 Years", inStock: true },
        { name: "9 Years", inStock: false },
        { name: "10 Years", inStock: false },
      ],
      reviews: [{ average: 4 }, { totalCount: 552 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$200",
      path: "/",
    },
    {
      id: 13,
      type: "Jeans",
      icon1: "/clothes/Kids/Jeans/CalvinKlein/1.jpg",
      icon2: "/clothes/Kids/Jeans/CalvinKlein/2.jpg",
      icon3: "/clothes/Kids/Jeans/CalvinKlein/3.jpg",
      icon4: "/clothes/Kids/Jeans/CalvinKlein/1.jpg",
      alt: "",
      brand: "Calvin Klein",
      name: "Quilted Plaid Overshirt",
      colors: [
        {
          name: "White",
          class: "bg-blue-900",
          selectedClass: "ring-blue-900",
        },
      ],
      sizes: [
        { name: "2 Years", inStock: true },
        { name: "6 Years", inStock: false },
        { name: "8 Years", inStock: true },
        { name: "12 Years", inStock: true },
        { name: "14 Years", inStock: false },
        { name: "16 Years", inStock: false },
      ],
      reviews: [{ average: 3 }, { totalCount: 444 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$120",
      path: "/",
    },
    {
      id: 14,
      type: "Shirt",
      icon1: "/clothes/Kids/Shirt/Adidas/White/1.jpg",
      icon2: "/clothes/Kids/Shirt/Adidas/White/2.jpg",
      icon3: "/clothes/Kids/Shirt/Adidas/Black/3.jpg",
      icon4: "/clothes/Kids/Shirt/Adidas/Black/4.jpg",
      alt: "",
      brand: "Adidas",
      name: "Adidas - TREFOIL TEE",
      colors: [
        {
          name: "Black",
          class: "bg-black",
          selectedClass: "ring-black",
        },
        {
          name: "White",
          class: "bg-white",
          selectedClass: "ring-gray-500",
        },
      ],
      sizes: [
        { name: "12 Years", inStock: true },
        { name: "14 Years", inStock: false },
        { name: "15 Years", inStock: false },
        { name: "16 Years", inStock: false },
      ],
      reviews: [{ average: 5 }, { totalCount: 1099 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$119",
      path: "/",
    },
    {
      id: 15,
      type: "Snow Suit",
      icon1: "/clothes/Kids/SnowSuit/TommyHilfiger/Pink/1.jpg",
      icon2: "/clothes/Kids/SnowSuit/TommyHilfiger/Pink/2.jpg",
      icon3: "/clothes/Kids/SnowSuit/TommyHilfiger/Black/3.jpg",
      icon4: "/clothes/Kids/SnowSuit/TommyHilfiger/Black/2.jpg",
      alt: "",
      brand: "Tommy Hilfiger",
      name: "TOMMY SOLID SKISUIT",
      colors: [
        {
          name: "Black",
          class: "bg-black",
          selectedClass: "ring-black",
        },
        {
          name: "White",
          class: "bg-white",
          selectedClass: "ring-gray-500",
        },
      ],
      sizes: [
        { name: "XS", inStock: true },
        { name: "S", inStock: false },
        { name: "M", inStock: true },
        { name: "L", inStock: false },
        { name: "XL", inStock: false },
      ],
      reviews: [{ average: 4 }, { totalCount: 222 }],
      description:
        ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
      highlights: [
        " 1 Hand cut and sewn locally",
        "Dyed with our proprietary colors",
        "Pre-washed & pre-shrunk",
        "Ultra-soft 100% cotton",
      ],
      details:
        'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
      cost: "$200",
      path: "/",
    },
  ],
];
