export const cardsData = [
  [{
    /* For Men */
    id: 1,
    type: "Jacket",
    icon1: "/clothes/Men/Jacket/TommyHilfiger/Black/1.jpg",
    icon2: "/clothes/Men/Jacket/TommyHilfiger/Black/2.jpg",
    icon3: "/clothes/Men/Jacket/TommyHilfiger/Black/3.jpg",
    icon4: "/clothes/Men/Jacket/TommyHilfiger/Red/1.jpg",
    alt: "",
    brand: "Tommy Hilfiger",
    name: "MIX DOWN HOODED PUFFER JACKET",
    colors: [
      { name: "Black", class: "bg-black-900", selectedClass: "ring-black-200" },
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "XXL", inStock: true },
    ],
    reviews: [{ average: 3 }, { totalCount: 25 }],
    description:
      ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      " 1 Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$500",
    path: "/",
  },
  {
    id: 2,
    type: "Jeans",
    icon1: "/clothes/Men/Jeans/Levis/Black/1.jpg",
    icon2: "/clothes/Men/Jeans/Levis/Blue/2.jpg",
    icon3: "/clothes/Men/Jeans/Levis/DarkBlue/3.jpg",
    icon4: "/clothes/Men/Jeans/Levis/SkyBlue/4.jpg",
    alt: "",
    brand: "Levis",
    name: "Relaxed Straight",
    colors: [
      { name: "Black", class: "bg-black-900", selectedClass: "ring-black-200" },
      { name: "Blue", class: "bg-blue-950", selectedClass: "ring-blue-950" },
      { name: "Dark Blue", class: "bg-red-900", selectedClass: "ring-blue-950" },
      { name: "Sky Blue", class: "bg-black-900", selectedClass: "ring-blue-500" },
    ],
    sizes: [
      { name: "29", inStock: true },
      { name: "30", inStock: true },
      { name: "31", inStock: true },
      { name: "32", inStock: true },
      { name: "33", inStock: true },
      { name: "34", inStock: true },
      { name: "36", inStock: true },
      { name: "38", inStock: true },
      { name: "40", inStock: true },
    ],
    reviews: [{ average: 3 }, { totalCount: 25 }],
    description:
      ' 1 The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      " 1 Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$300",
    path: "/",
  },],
  [],
  []
  
  {
    id: 2,
    icon: "/Products/2.webp",
    alt: "",
    name: "Samsung CF591 Series Curved 27-Inch FHD",
    colors: [
      { name: "White", class: "bg-white", selectedClass: "ring-grey-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 4 }, { totalCount: 17 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$610",
    path: "/",
  },
  {
    id: 3,
    icon: "/Products/3.webp",
    alt: "",
    name: "Blue Yeti USB Microphone Blackout Edition",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 5 }, { totalCount: 180 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$120",
    path: "/",
  },
  {
    id: 4,
    icon: "/Products/4.webp",
    alt: "",
    name: "DYMO LabelWriter 450 Turbo Thermal",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 3 }, { totalCount: 65 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$410",
    path: "/",
  },
  {
    id: 5,
    icon: "/Products/5.webp",
    alt: "",
    name: "Pryma Headphones, Rose Gold Wite & Grey",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 2 }, { totalCount: 11 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "White",
    cost: "$180",
    path: "/",
  },
  {
    id: 6,
    icon: "/Products/6.webp",
    alt: "",
    name: "Sony WH-1000XM4 Wireless Headphones",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 2 }, { totalCount: 3 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "Grey",
    cost: "$350.00",
    path: "/",
  },
  {
    id: 7,
    icon: "/Products/7.webp",
    alt: "",
    name: "Pryma Headphones, Rose Gold & Grey",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 5 }, { totalCount: 1546 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "White",
    cost: "$999",
    path: "/",
  },
  {
    id: 8,
    icon: "/Products/8.webp",
    alt: "",
    name: "Nikon D5600 E567 Digital SLR Camera",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 5 }, { totalCount: 9832 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$700",
    path: "/",
  },
  {
    id: 9,
    icon: "/Products/9.webp",
    alt: "",
    name: "Razer Blade 15 I5 12400 Gaming Laptop",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 2 }, { totalCount: 15 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    cost: "$1799",
    path: "/",
  },
  {
    id: 10,
    icon: "/Products/10.webp",
    alt: "",
    name: "Logitech MX 100NC 3-120 Wireless Mouse",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 5 }, { totalCount: 124 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "White",
    cost: "$99",
    path: "/",
  },
  {
    id: 11,
    icon: "/Products/1.webp",
    alt: "",
    name: "Logitech MX 100NC 3-120 Wireless Mouse",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 0 }, { totalCount: 1 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "White",
    cost: "$99",
    path: "/",
  },
  {
    id: 12,
    icon: "/Products/2.webp",
    alt: "",
    name: "Logitech MX 100NC 3-120 Wireless Mouse",
    colors: [
      { name: "Red", class: "bg-red-900", selectedClass: "ring-red-200" },
    ],
    sizes: [
      { name: "XXS", inStock: false },
      { name: "XS", inStock: true },
      { name: "S", inStock: true },
      { name: "M", inStock: true },
      { name: "L", inStock: true },
      { name: "XL", inStock: true },
      { name: "2XL", inStock: true },
      { name: "3XL", inStock: true },
    ],
    reviews: [{ average: 2 }, { totalCount: 77 }],
    description:
      'The Basic Tee 6-Pack allows you to fully express your vibrant personality with three grayscale options. Feeling adventurous? Put on a heather gray tee. Want to be a trendsetter? Try our exclusive colorway: "Black". Need to add an extra pop of color to your outfit? Our white tee has you covered.',
    highlights: [
      "Hand cut and sewn locally",
      "Dyed with our proprietary colors",
      "Pre-washed & pre-shrunk",
      "Ultra-soft 100% cotton",
    ],
    details:
      'The 6-Pack includes two black, two white, and two heather gray Basic Tees. Sign up for our subscription service and be the first to get new, exciting colors, like our upcoming "Charcoal Gray" limited release.',
    color: "White",
    cost: "$99",
    path: "/",
  },
];
